spring:
    #redis 配置            
    redis:
        host: localhost
        password:
        timeout: 3000
        database: 0
        port: 6379
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1
          
#服务器相关配置       
server:
  port: 8080
  context-path: /jartisan
  connection-timeout: 30000
  #tomcat相关配置
  #tomcat:
   # basedir: /opt
    #max-connections: 3000 可选
    #max-threads: 3000     可选
    
    #accesslog:
     #pattern: "%t %a %r %s (%D ms)"
      #enabled: true
      #directory: /logs
  undertow:
    accesslog:
      pattern: combined
      enabled: true
      dir: /opt/logs
      
#监控  
management:
  security:
    enabled: false
    
#数据库访问配置
# 使用druid数据源
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql:///crm?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        username: root
        password: killer3
        
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 100
        initialSize: 3
        maxWait: 60000
        minIdle: 3
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
    slave:
        url: jdbc:mysql:///crm?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        username: root
        password: killer3
        
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 100
        initialSize: 3
        maxWait: 60000
        minIdle: 3
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      
#第三方系统地址
domain:
  name: dev.mbs.api
